
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "memberId" : "tes11256789",
  "password" : "123123",
  "passwordConfirm" : "123123",
  "email" : "asdf@naver.com",
  "phone_number": "010-1111-1111",
  "name" : "철수" ,
  "address" :  "서울",
  "address_detail" : "서울",
  "gender": "남성",
  "birth": "",
  "policy": true,
  "invite_user": "asdf"
}

###

POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "memberId" : "tes11256789",
  "password" : "123123"
}

###

POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "memberId" : "tes1125",
  "password" : "123123"
}

###

GET http://localhost:8080/api/member
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXMxMTI1Njc4OSIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NjI5NDgyNDl9.BP-BHXWX3pCIOO-ku1b9JUAmOFFAOVyuQjmcyqRzZ8fwVmaCT9_loafFGGa0vacFuuxOtimHxMD0Rb-O2qAcxA
Refresh-Token: eyJKV1RfSEVBREVSX1BBUkFNX1RZUEUiOiJoZWFkZXJUeXBlIiwiYWxnIjoiSFM1MTIifQ.eyJleHAiOjE2NjM1NTEyNDl9.0d4mpLKJlmyFLGdwEWZzodPpW9tI_rd3wEXY7Imt2kYn26LxDz6ZcoxDdZ0pwv33Ys4BvwoPKKHE5zmxzcq-yA
Accept: application/json

###

GET http://localhost:8080/api/member
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXMxMTI1IiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2MjkwNDczNH0.4gNAS9yga5Gq-GPNJqeUwXP52bo7JP4CFcYSZ0e72WHluxkjCdS3l6xWl0mC_beiIYRg0aa1mPgllRJ5IbOcrA
Refresh-Token: eyJKV1RfSEVBREVSX1BBUkFNX1RZUEUiOiJoZWFkZXJUeXBlIiwiYWxnIjoiSFM1MTIifQ.eyJleHAiOjE2NjM1MDc3MzR9.3P0Xm-hNQxQVFt-Ug14_WC_kf_icw81F6i0k5ImxAxHQeSIN4OX9jZ2vE7imJmvDzZusdr5enzdrJJbbEio8Og

Accept: application/json

###

POST http://localhost:8080/api/member/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXMxMTI1Njc4OSIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NjI5NDgyNDl9.BP-BHXWX3pCIOO-ku1b9JUAmOFFAOVyuQjmcyqRzZ8fwVmaCT9_loafFGGa0vacFuuxOtimHxMD0Rb-O2qAcxA
Refresh-Token: eyJKV1RfSEVBREVSX1BBUkFNX1RZUEUiOiJoZWFkZXJUeXBlIiwiYWxnIjoiSFM1MTIifQ.eyJleHAiOjE2NjM1NTEyNDl9.0d4mpLKJlmyFLGdwEWZzodPpW9tI_rd3wEXY7Imt2kYn26LxDz6ZcoxDdZ0pwv33Ys4BvwoPKKHE5zmxzcq-yA
Content-Type: application/json


###